### ISSUE TITLE
le bouton share ne fonctionne pas

### ISSUE THREAD

**Issue by totorobin** [totorobin/poker#3]
le bouton share ne fonctionne pas :
```
index-602a36d7.js:1 TypeError: Cannot read properties of undefined (reading 'writeText')
    at c (index-602a36d7.js:17:27193)
    at fn (index-602a36d7.js:1:13375)
    at mt (index-602a36d7.js:1:13454)
    at HTMLDivElement.n (index-602a36d7.js:1:56892)
```

**Comment by totorobin** [comment]
doublon avec #4
